dynamic jsonData = {
  "income": [
    {"id": 1, "title": "Balance(B/D)", "amount": "1"},
    {"id": 2, "title": "আয় - ব্যয়", "amount": "2"},
    {"id": 3, "title": "Withdraw Fixed Deposit", "amount": "3"},
    {"id": 4, "title": "সঞ্চয়পত্র বিক্রয়", "amount": "4"},
    {"id": 5, "title": "Any Interest", "amount": "5"},
    {"id": 6, "title": "অন্যান্য উৎস থেকে নগদ", "amount": "6"},
    {"id": 7, "title": "ঋণ গ্রহণ", "amount": "7"},
    {"id": 8, "title": "ক্লাস পরীক্ষা ২০১৯", "amount": "8"},
    {"id": 10, "title": "Bonus", "amount": "9"},
    {"id": 11, "title": "বেতন", "amount": "10"},
    {"id": 12, "title": "Gift", "amount": "11"},
    {"id": 13, "title": "Rent", "amount": "12"},
    {"id": 14, "title": "প্রতিফলন", "amount": "13"},
    {"id": 15, "title": "Freelancing", "amount": "14"},
    {"id": 16, "title": "Dividends", "amount": "15"},
    {"id": 17, "title": "প্রত্যাখ্যান", "amount": "16"},
    {"id": 18, "title": "Sales", "amount": "17"},
    {"id": 19, "title": "Interest Income", "amount": "18"},
    {"id": 20, "title": "Consulting Fees", "amount": "19"},
    {"id": 16, "title": "Dividends", "amount": "20"},
    {"id": 17, "title": "প্রত্যাখ্যান", "amount": "21"},
    {"id": 18, "title": "Sales", "amount": "22"},
    {"id": 19, "title": "Interest Income", "amount": "23"},
    {"id": 20, "title": "Consulting Fees", "amount": "24"},
    {"id": 20, "title": "Consulting Fees", "amount": "24"},
    {"id": 38, "title": "মোট =", "amount": "25"},
    {"id": 38, "title": "মোট =", "amount": "26"},
    {"id": 38, "title": "মোট =", "amount": "27"},
  ],
  "expense": [
    {"id": 1, "title": "ব্যয় আয়ের উপরে", "amount": "2000"},
    {"id": 2, "title": "Expenses Over Income", "amount": "3000"},
    {"id": 3, "title": "ব্যাংকে আমানত", "amount": "2500"},
    {"id": 4, "title": "Transfer to Fixed Deposit", "amount": "1800"},
    {"id": 5, "title": "সঞ্চয়পত্র ক্রয়", "amount": "2100"},
    {"id": 6, "title": "Charges (Bank/Others)", "amount": "1500"},
    {"id": 7, "title": "অন্যান্য সম্পত্তি ক্রয়", "amount": "2200"},
    {"id": 8, "title": "ঋণ পরিশোধ", "amount": "4000"},
    {"id": 10, "title": "Groceries", "amount": "500"},
    {"id": 11, "title": "Utilities", "amount": "800"},
    {"id": 12, "title": "ভাড়া", "amount": "1200"},
    {"id": 13, "title": "Insurance", "amount": "1000"},
    {"id": 20, "title": "Childcare", "amount": "1500"},
    {"id": 30, "title": "Selling Assets", "amount": "2500"},
    {"id": 9, "title": "মোট =", "amount": "56000"},
    {"id": 11, "title": "Utilities", "amount": "800"},
    {"id": 12, "title": "ভাড়া", "amount": "1200"},
    {"id": 13, "title": "Insurance", "amount": "1000"},
    {"id": 20, "title": "Childcare", "amount": "1500"},
    {"id": 30, "title": "Selling Assets", "amount": "2500"},
    {"id": 9, "title": "মোট =", "amount": "56000"}
  ]
};
